version: "3.9"

services:
  app:
    build:
        dockerfile: Dockerfile
    container_name: xode-wallet-api
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - 3008:3008

  copy-xode-wallet-env:
    build:
        dockerfile: Dockerfile
    container_name: copy-xode-wallet-env
    platform: linux/amd64
    volumes:
      - /var/www/xgame-apis-xode-wallet-api/.env:/temp/.env
    command: sh -c "cp /temp/.env /app/.env && exit"
